# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'CreateRoom.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(1200, 800)
        self.widget1 = QtWidgets.QWidget(Dialog)
        self.widget1.setGeometry(QtCore.QRect(0, 0, 1200, 800))
        self.widget1.setAutoFillBackground(False)
        self.widget1.setStyleSheet("QWidget#widget1{\n"
"background-color:qlineargradient(spread:pad, x1:0.527, y1:0.607955, x2:0.528, y2:1, stop:0 rgba(34, 71, 114, 255), stop:1 rgba(255, 255, 255, 255))}")
        self.widget1.setObjectName("widget1")
        self.label = QtWidgets.QLabel(self.widget1)
        self.label.setGeometry(QtCore.QRect(390, 50, 450, 450))
        self.label.setStyleSheet("font: 45pt;\n"
"color:rgb(255,255,255)")
        self.label.setObjectName("label")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate("Dialog", "Create Room"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
